# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAndUIKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAndUIKitDemo
  pod 'SnapKit' # Swift版 Masonry
  pod 'Alamofire' # Swift版 Afnetworking
  pod 'Kingfisher' # Swift版 SDWebImage
end
